
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.30.77:3306/db_ktvApplet?userSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #type-aliases-package: com.es.enjoystudy.entity
  mapper-locations: classpath:mapper/*.xml
